
[window]
opacity = 1.0
padding.x = 10
padding.y = 10

[font]
size = 13.0

[terminal.shell]
program = "/bin/bash"
args = ["--login"]

# Breeze Light (KDE Plasma)
[colors.primary]
background = "#fcfcfc"
foreground = "#232629"

[colors.cursor]
text   = "#fcfcfc"
cursor = "#232629"

[colors.selection]
text       = "#fcfcfc"
background = "#3daee9"

[colors.normal]
black   = "#232629"
red     = "#ed1515"
green   = "#11d116"
yellow  = "#f67400"
blue    = "#1d99f3"
magenta = "#9b59b6"
cyan    = "#1abc9c"
white   = "#fcfcfc"

[colors.bright]
black   = "#7f8c8d"
red     = "#c0392b"
green   = "#1cdc9a"
yellow  = "#fdbc4b"
blue    = "#3daee9"
magenta = "#8e44ad"
cyan    = "#16a085"
white   = "#ffffff"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
